project:
  type: website
  output-dir: docs


website:
  title: "Hayatımızda Bilim"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme:
      light: cosmo
      dark: solar
    css: styles.css
    toc: true
    logo: Logo.png

editor: visual

